MobelZonen2/Areas/Admin/Controllers/AKategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RepoMZ2;

namespace MobelZonen2.Areas.Admin.Controllers
{
    
    public class AKategoriController : Controller
    {
        private KategoriFac kf = new KategoriFac();
        private SEOFac sf = new SEOFac();

        // GET: Admin/AKategori
        
        public ActionResult Index()
        {
            return View(kf.GetAll());
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            kf.Delete(id);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Kategori kat)
        {
            kf.Insert(kat);
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            EditKat editkat = new EditKat();
            editkat.Kategori = kf.Get(id);
            if (editkat.Kategori.SEOID > 1)
            {
                editkat.Seo = sf.Get(editkat.Kategori.SEOID);
            }
            else
            {
                SEO seo = new SEO();
                editkat.Seo = seo;
            }


            return View(editkat);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(Kategori kat)
        {
            kf.Update(kat);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditSEO(SEO seo, int katID)
        {
            if (seo.ID > 1)
            {
                if (ModelState.IsValid)
                {
                    sf.Update(seo);
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    int id = sf.Insert(seo);
                    kf.UpdateField("SEOID", id, katID);
                }
            }


            return RedirectToAction("Index");
        }
    }
}

//[Authorize]
//[AllowAnonymous]
//[Authorize(Users = "40,42,55")]
//[Authorize(Roles = "Administrators")]

MobelZonen2/Areas/Admin/Controllers/AKontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RepoMZ2;
using System.IO;

namespace MobelZonen2.Areas.Admin.Controllers
{
    public class AKontaktController : Controller
    {
        KontaktFac kf = new KontaktFac();

        // GET: Admin/AKontakt
        public ActionResult Index()
        {
            return View(kf.Get(1));
        }

        [HttpPost]
        public ActionResult Edit(Kontakt kontakt)
        {
            kf.Update(kontakt);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase billede)
        {
            if (billede != null)
            {
                Uploader uploader = new Uploader();
                string path = Request.PhysicalApplicationPath + "Content/Billeder/Kontakt/";

                string fil = uploader.UploadImage(billede, path, 255, true);

                Kontakt kon = kf.Get(1);
                kon.Billede = Path.GetFileName(fil);

                kf.Update(kon);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.MSG = "Der er ikke valgt et billede!";
                return View("Index", kf.Get(1));
            }
            
        }
    }
}

MobelZonen2/Areas/Admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobelZonen2.Areas.Admin.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Admin/Default
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

MobelZonen2/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RepoMZ2;

namespace MobelZonen2.Controllers
{
    public class DataController : Controller
    {

        KategoriFac katF = new KategoriFac();
        KontaktFac konF = new KontaktFac();
        // GET: Data
        [ChildActionOnly]
        public ActionResult Menu()
        {
            return PartialView(katF.GetAll());
        }

        [ChildActionOnly]
        public ActionResult Footer()
        {
            return PartialView(konF.Get(1));
        }

    }
}

MobelZonen2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using RepoMZ2;
using RepoMZ2.Factories;

namespace MobelZonen2.Controllers
{
    public class HomeController : Controller
    {

        KontaktFac kf = new KontaktFac();


        // GET: Home
        public ActionResult Index()
        {
           
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string email, string adgangskode)
        {
            BrugerFac bf = new BrugerFac();
            Bruger bruger = bf.Login(email.Trim(), Crypto.Hash(adgangskode.Trim()));

            if (bruger.ID > 0)
            {
                FormsAuthentication.SetAuthCookie(bruger.ID.ToString(), false);
                Response.Redirect("/Admin/Default/Index/");
            }

            return Redirect("/Home/Login/");
        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index");
        }

        public ActionResult Kontakt()
        {
            return View(kf.Get(1));
        }

        public ActionResult MailForm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MailForm(string Email, string Emne, string Besked)
        {
            MailFac mf = new MailFac("smtp.gmail.com", "webitgrenaa@gmail.com", "webitgrenaa@gmail.com", "Obsengud78", 587);

            mf.Send(Emne, Email + "<br/>" + Besked, "hto@djes.dk");

            ViewBag.MSG = "Din besked er sendt!";

            return View();

        }


    }
}

MobelZonen2/Controllers/ProduktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RepoMZ2;

namespace MobelZonen2.Controllers
{
    public class ProduktController : Controller
    {
        KategoriFac kf = new KategoriFac();
        ProduktFac pf = new ProduktFac();
        SEOFac SF = new SEOFac();
        // GET: Produkt
        public ActionResult ListProdukter(int id)
        {
            ProduktListe pl = new ProduktListe();

            pl.SEO = SF.Get(kf.Get(id).SEOID);
            pl.KategoriNavn = kf.Get(id).Navn;
            pl.Produkter = pf.GetBy("KatID", id);

            return View(pl);
        }
    }
}

MobelZonen2/Areas/Admin/Views/AKategori/Add.cshtml
@{
    ViewBag.Title = "Add";
}
@section head
{

    <link href="~/Content/Styles/AdminMain.min.css" rel="stylesheet" />

}
<h1>Tilføj kategori</h1>

<form action="/Admin/AKategori/Add/" method="POST">
    <table class="formTB">
        <tr>
            <td><b>Navn:</b></td>
            <td><input name="Navn" type="text"/></td>
        </tr>
        <tr>
            <td><b>Sortering:</b></td>
            <td><input name="Sortering" type="text" /></td>
        </tr>
        <tr>
            <td rowspan="2">
                <input type="submit" value="Gem" />
           
            </td>
        </tr>
    </table>
</form>

MobelZonen2/Areas/Admin/Views/AKategori/Edit.cshtml
@model RepoMZ2.EditKat
@{
    ViewBag.Title = "Edit";
}
@section head
{

    <link href="~/Content/Styles/AdminMain.min.css" rel="stylesheet" />

}
<h1>Rediger Kategori</h1>
<div class="row">
    <div class="col-sm-6">
        <h2>Kategori data</h2>

        <form action="/Admin/AKategori/Edit/" method="POST">
            <table class="formTB">
                <tr>
                    <td><b>Navn:</b></td>
                    <td><input name="Navn" type="text" value="@Model.Kategori.Navn" /></td>
                </tr>
                <tr>
                    <td><b>Sortering:</b></td>
                    <td><input name="Sortering" type="text" value="@Model.Kategori.Sortering" /></td>
                </tr>
                <tr>
                    <td rowspan="2">
                        <input type="submit" value="Gem" />
                        <input type="hidden" name="ID" value="@Model.Kategori.ID" />
                    </td>
                </tr>
            </table>
        </form>

    </div>
    <div class="col-sm-6">
        <h2>SEO</h2>
        <form action="/Admin/Akategori/EditSEO/" method="POST">
            <table class="formTB">
                <tr>
                    <td>Title:</td>
                    <td><input type="text" name="Title" value="@Model.Seo.Title" /></td>
                </tr>
                <tr>
                    <td>Keywords:</td>
                    <td><textarea name="Keywords">@Model.Seo.Keywords</textarea></td>
                </tr>
                <tr>
                    <td>Description:</td>
                    <td><textarea name="Description">@Model.Seo.Description</textarea></td>
                </tr>
                <tr>
                    <td rowspan="2">
                        <input type="submit" value="Gem" />
                        <input type="hidden" name="ID" value="@Model.Seo.ID" />
                        <input type="hidden" name="katID" value="@Model.Kategori.ID" />
                    </td>
                </tr>
            </table>


        </form>
    </div>
</div>
    

MobelZonen2/Areas/Admin/Views/AKategori/Index.cshtml
@using RepoMZ2
@model System.Collections.Generic.List<RepoMZ2.Kategori>
@{
    ViewBag.Title = "Index";
}
@section head
{

    <link href="~/Content/Styles/AdminMain.min.css" rel="stylesheet" />

}
<h1>Rediger kategorier</h1>
<p><button onclick="window.location='/Admin/AKategori/Add/';">Opret ny kategori</button></p>


<div class="listTB">
    

    @foreach (Kategori kat in Model)
    {
        <div class="rowi">
            <div>@kat.Navn</div>

            <div><a href="/Admin/Akategori/Edit/@kat.ID/">Rediger</a> <a href="/Admin/Akategori/Delete/@kat.ID/" onclick="javascript:return confirm('Er du sikker på at du vil slette @kat.Navn?');">Slet</a>
            </div>
            <div style="clear: both;"></div>
        </div>    
    }

</div>

MobelZonen2/Areas/Admin/Views/AKontakt/Index.cshtml
@model RepoMZ2.Kontakt
@{
    ViewBag.Title = "Index";
}

<h2>Rediger Kontakt</h2>

<table>
    <tr>
        <td>
            <form action="/Admin/AKontakt/Edit/" method="POST">
                Navn:<br/>
                <input type="text" name="Navn" value="@Model.Navn" />
                <br/>
                Adresse:<br />
                <input type="text" name="Adresse" value="@Model.Adresse" />
                <br/>
                PostNr:<br />
                <input type="text" name="PostNr" value="@Model.PostNr" />
                <br/>
                By Navn:<br />
                <input type="text" name="Bynavn" value="@Model.Bynavn" />
                <br/>
                Tlf:<br />
                <input type="text" name="Tlf" value="@Model.Tlf" />
                <br/>
                Fax:<br />
                <input type="text" name="Fax" value="@Model.Fax" />
                <br/>
                E-mail:<br />
                <input type="text" name="Email" value="@Model.Email" />
                <br/>
                <textarea name="Tider">@Model.Tider</textarea>
                <input type="submit" value="Gem"/>
                <input name="ID" type="hidden" value="@Model.ID"/>
                <input name="Billede" type="hidden" value="@Model.Billede" />
            </form>
        </td>
        <td>
            <form action="/Admin/AKontakt/Upload/" method="POST" enctype="multipart/form-data">
                <img src="/Content/Billeder/Kontakt/@Model.Billede"/>
                <br/>
                <input name="billede" type="file"/>
                <input type="submit" value="Gem"/>
                @ViewBag.MSG
            </form>
        </td>
    </tr>
</table>

MobelZonen2/Areas/Admin/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MobelZonen2/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Super CMS</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("head", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1>Super CMS</h1>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Admin/AKategori/Index/">Kategorier</a></li>
                    <li><a href="/Home/Signout/">Log-ud</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MobelZonen2/Views/Data/Footer.cshtml
@model RepoMZ2.Kontakt
    
@Model.Navn, @Model.Adresse, @Model.PostNr @Model.Bynavn, @Model.Tlf, @Model.Email

MobelZonen2/Views/Data/Menu.cshtml
@using RepoMZ2
@model List<RepoMZ2.Kategori>


    @foreach (Kategori k in Model)
    {
        <a href="/Produkt/ListProdukter/@k.ID/" class="menuLinks">@k.Navn</a><br/>
    }

MobelZonen2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

MobelZonen2/Views/Home/Kontakt.cshtml
@model RepoMZ2.Kontakt
@{
    ViewBag.Title = "Kontakt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kontakt</h2>
<hr />

<table>
    <tr>
        <td>
            <p>
                <b>@Model.Navn</b>
                <br />
                @Model.Adresse
                <br />
                @Model.PostNr @Model.Bynavn
            </p>
            <p>
                @Model.Tlf
                <br />
                @Model.Fax
            </p>
            <p>
                @Model.Email
            </p>
            <p>
                @Html.Raw(Model.Tider)
            </p>
            <a href ="/Home/MailForm/">Send os en mail her!</a>

        </td>
        <td>
            <img src="/Content/Billeder/Kontakt/@Model.Billede" />
        </td>
    </tr>
</table>

MobelZonen2/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        .outer {
            display: table;
            position: absolute;
            height: 90%;
            width: 90%;
        }

        .middle {
            display: table-cell;
            vertical-align: middle;
        }

        .inner {
            font-family: arial;
            margin-left: auto;
            margin-right: auto;
            width: 200px;
            border: solid 1px gray;
            border-radius: 5px;
            padding: 20px;
            background-color: lightgray;
        }
        input {
            border: solid 1px gray;
            border-radius: 5px;
            padding: 3px;
        }
    </style>
</head>
<body>
    <div class="outer">
        <div class="middle">
            <div class="inner">

                @*@Crypto.Hash("admin")*@
                <form action="/Home/Login/" method="POST">
                    Email:
                    <br />
                    <input type="email" name="email" />
                    <br />
                    Password:
                    <br />
                    <input type="password" name="adgangskode" />
                    <br /><br />
                    <input type="submit" value="Log-in" />
                </form>
            </div>
        </div>
    </div>
</body>
</html>

MobelZonen2/Views/Home/MailForm.cshtml
@{
    ViewBag.Title = "MailForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Send os en mail</h2>

<form action="/Home/MailForm/" method="POST">

    Din email:<br/>
    <input type="text" name="Email"/>
    <br/>
    Emne:<br />
    <input type="text" name="Emne" />
    <br/>
    <textarea name="Besked" width="300"></textarea>
    <br/>
    <input type="submit" value="Send"/>
    @ViewBag.MSG
</form>

MobelZonen2/Views/Produkt/ListProdukter.cshtml
@using RepoMZ2
@model RepoMZ2.ProduktListe
@{
    ViewBag.Title = Html.Raw(Model.SEO.Title);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section head
{
  

    <meta name="keywords" content="@Html.Raw(Model.SEO.Keywords)"/>
    <meta name="description" content="@Html.Raw(Model.SEO.Description)"/>

}

<h2>@Model.KategoriNavn</h2>

@foreach (Produkt p in Model.Produkter)
{
    <table class="proTable">
        <tr>
            <td class="proTableLtd"><h2>@p.Navn</h2>pro.Tekst<br />Pris:@p.Pris kr.</td>
            <td class="proTableRtd"><img src="/Content/Billeder/@p.Billede" height="150" /></td>
        </tr>
    </table>

}

MobelZonen2/Views/Shared/_Layout.cshtml
@using System.ServiceModel.Configuration
@using RepoMZ2
<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/Styles/Main.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width"/>
  
    <title>@ViewBag.Title</title>

    @RenderSection("head", required: false)

</head>
<body>
    <div id="bannerBox">
    </div>
    <main id="contentWrapper">
        <nav id="vMenu">
            <div id="vMenuCon">
                <h1>Kattegorier</h1>

                @{
                    Html.RenderAction("Menu", "Data");
                }

            </div>

         

            <table id="linkTable">
                <tr>
                    <td class="linkImgTd"><img src="/Content/GFX/home.jpg" /></td>
                    <td class="linkLinkTd"><a href="#" class="Menu">Home</a></td>
                </tr>
                <tr>
                    <td class="linkImgTd"><img src="/Content/GFX/Info.jpg" /></td>
                    <td class="linkLinkTd"><a href="#" class="Menu">Information</a></td>
                </tr>
                <tr>
                    <td class="linkImgTd"><img src="/Content/GFX/print.jpg" /></td>
                    <td class="linkLinkTd"><a href="#" onclick="javascript:window.print();" class="Menu">Print</a></td>
                </tr>
                <tr>
                    <td class="linkImgTd"><img src="/Content/GFX/post.jpg" /></td>
                    <td class="linkLinkTd"><a href="/Home/Kontakt/" class="Menu">Kontakt</a></td>
                </tr>
                <tr>
                    <td class="linkImgTd"><img src="/Content/GFX/mail.jpg" /></td>
                    <td class="linkLinkTd"></td>
                </tr>
            </table>


        </nav>
        <div id="hMenu">
            <div id="hMenuCon">
           
            </div>
            <div id="nyhed">

            </div>
        </div>
        <div id="content">
            @RenderBody()
        </div>
        <div id="clear">
        </div>
    </main>
    <footer id="adress">
        @{
            Html.RenderAction("Footer", "Data");
        }
    </footer>

</body>
</html>